name: Benchmarks

permissions:
  contents: read

on:
  schedule:
    # runs once a week
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package '-Dmaven.test.skip'

    - name: Create Results Directory
      run: mkdir bench_results

    - name: Run JMH Benchmarks
      run: java -jar jgalgo-bench/target/benchmarks.jar -rf csv -rff bench_results/bench_results.csv "com.jgalgo.bench.impls.*"

    - name: Zip Results
      run: |
        tar -czf bench_results.tar.gz bench_results

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jmh-benchmarks-results
        path: bench_results.tar.gz
