name: Coverage

on:
  push:
    branches:
      - master

jobs:
  coverage_report:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo
      uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package -Dmaven.test.skip

    - name: Run JUnit Tests with Jacoco coverage
      run: mvn --batch-mode clean jacoco:prepare-agent '-Dtest=com.jgalgo.test.*Test' test jacoco:report

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-coverage-badge: true
        badges-directory: target/site/jacoco/badges

    - name: Publish Jacoco Coverage Report
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: coverage
        clean: true
        folder: target/site/jacoco
        target-folder: .
