name: JavaDoc

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
        cache: maven

    - name: Generate Javadoc with Maven
      run: mvn javadoc:aggregate -pl jgalgo-core
      shell: bash

    - name: Deploy to GitHub Page 🚀 with Maven
      uses: JamesIves/github-pages-deploy-action@v4.4.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: javadoc
        clean: true
        folder: jgalgo-core/target/site/apidocs
        target-folder: .
