name: SpotBugs

permissions:
  contents: read

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get repo
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package '-Dmaven.test.skip'

    - name: statically analyze code using SpotBugs
      run: mvn --batch-mode spotbugs:check -pl jgalgo-core
